// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbsyztaloizdmswbyouy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impic3l6dGFsb2l6ZG1zd2J5b3V5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3Njg5MzcsImV4cCI6MjA1NDM0NDkzN30.4jyd5wLkYjxWQ3-l4mwt6J1qLYFLWSjf6l4wRhXg4ek";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);